

# Path and Oh My Zsh settings
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Completion and behavior settings
# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"

# Auto-update settings
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# zstyle ':omz:update' frequency 13

# Other settings
# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins and Oh My Zsh initialization
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Additional configurations
# export MANPATH="/usr/local/man:$MANPATH"
# export LANG=en_US.UTF-8
# export EDITOR='vim'

# Vi mode and cursor settings
bindkey -v
export KEYTIMEOUT=1

function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
        echo -ne '\e[1 q'
    elif [[ ${KEYMAP} == main ]] || [[ ${KEYMAP} == viins ]] || [[ ${KEYMAP} = '' ]] || [[ $1 = 'beam' ]]; then
        echo -ne '\e[5 q'
    fi
}
zle -N zle-keymap-select

zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init

echo -ne '\e[5 q'  # Set cursor shape on startup
preexec() { echo -ne '\e[0 q' ;}  # Set cursor shape for each new prompt

